<div align="center">
    <img src="recursos/img/logoitqv1.jpg" width="200">
</div>

**0.1 PAO25-25- NumPy**

<p align="center">
  <img src="recursos/img/python_logo.png" width="200">
</p>

Kerly Piclo

**Fecha:** 06/07/2026

**Repositorio:** [Link del repositorio de GitHub]

(https://github.com/kelapilco/machine-1-2026-nocturno.git)

**1 NumPY ndarray**

. NumPy (Num erical Py thon) es la de factor libreria estandar para analisis numerico en Python

. Estructura de datis multifuncionales eficientes (escrita en C): ndarry

. Ayuda al procedimiento de datos(np.whare)


In [5]:
#import libreria
import numpy as np


**1.1 Performance Sample, NumPy vs Plain Python**

In [6]:
my_list = list(range(10000000)) #Utilizando lista Python
%time my_list = [x * 2 for x in my_list]


CPU times: total: 1.22 s
Wall time: 1.3 s


In [7]:
my_arr = np.arange(10000000) #Ytilizando NumPy Array
%time my_arr2 = my_arr *2

CPU times: total: 46.9 ms
Wall time: 37.7 ms


**Formas de crear ndarrays**

In [8]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)


[[  2  71   0  34]
 [  2 171 -35  34]]


In [13]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))


[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [14]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [15]:
# Generar arrays con valores fijos
print(np.zeros(2)) # 1D
print(np.ones((4,3))) # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**1.3 Obtener informaciòn ndarray** 

In [16]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [17]:
print(my_ndarray.argmax()) # índice del valor más alto
print(np.amax(my_ndarray))
print(my_ndarray.argmin()) # índice del valor más bajo
print(np.amin(my_ndarray))
print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos␣a 0

1
71
2
0
(array([0, 1, 3]),)


In [18]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [19]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones


4
(4,)
1


**Redimencionar los datos**

In [20]:
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]]) # matrix 1x8
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim)

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [21]:
new_dims = my_ndarray.reshape(2, 4) # cambiar las dimensiones a 2x4
print(new_dims)
print(new_dims.ndim)


[[  0  71  21  19]
 [213 412 111  98]]
2


In [22]:
new_dims = my_ndarray.reshape(4, 2) # cambiar las dimensiones a 4x2
print(new_dims)
print(new_dims.ndim)


[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [23]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)


(3, 1)
[[100]
 [ 10]
 [  1]]


In [24]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten())


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [25]:
# reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2,-1)) # el segundo valor se infiere del primero

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


**Manipulacion de ndarray**

In [26]:
# Cambiar ejes
new_dims = np.arange(16).reshape(8,2)
print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [27]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims, axis = None))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [28]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)


[ 2  9 10 17]


In [29]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]
print(np.hstack((a1,a2))) # una al lado de la otra
print(np.hstack((a1,a2)).shape)
print(np.vstack((a1,a2))) # una encima de la otra
print(np.vstack((a1,a2)).shape)


[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [30]:
array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[3, 5], [7, 9]])
print(np.concatenate((array1, array2), axis = 0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [31]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, 2, axis = 0)) # divide array en 2 partes iguales
print(np.array_split(array, 3)) # divide array en 3 partes "iguales"


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [32]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, [3], axis = 1)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [33]:
split = np.array_split(array, [3], axis = 1)
print(split[0][3][0])


12


In [35]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0)) # divide array por la fila 1 y 3
print(np.array_split(array, [1, 3], axis = 1)) # divide array por la columna 1␣y 3
# axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

**Indice y Slicing**

**.** De manera anàloga a ìndice y slincing para listas

In [36]:
array = np.arange(10, 16)
print(array)
print(array[-1]) # acceso unidimensional
print(array[:-1]) # slice


[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [37]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [38]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])
print(array[1][2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


**NumPy es row mejor**

In [39]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3) # by default, row major
print(row_major)


[[1 2 3]
 [4 5 6]]


In [40]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C') # by default, row major
print(row_major)
col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F') # col major
print(col_major)


[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


**slice**

In [41]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[1:3, 2::2])


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [42]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


**Diferencia entre indice y slincing listas y ndarray**

**.** ¡Retornar una referencia, no una copa!

In [43]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2] # devuelve una copia
print(my_copy)
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [44]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5] # devuelve una referencia
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [45]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy() # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


**.** Permite asignar valores a un corte

In [46]:
array = np.arange(10)
print(array)
print(array[0:3])
array[0:3] = -1
print(array)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


**.** Slicing condicionales (mask)**

In [49]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array %2 == 0
print(mask)
print(array[mask])

print(array[array %2 == 0])

array[mask] = 0
print(array)


[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [50]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [51]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array % 2 == 0
print(mask)

array_par = array[mask] # devuelve una copia
print(array_par)

array_par[0] = -10
print(array)
print(array_par)


[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


**.** Acceso a multiples valores con listado de indice

In [53]:
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[[1,2]]) #selecting rows
print(array[:,[1,2]]) #selecting columns

# cross product of indexes
print(array[[1,2],:][:,[1,2]])

print(array[np.ix_([1,2],[1,2])]) # built in ix_

ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Fuciones màtematicas**

**.** Aplicar funciones entre escalares y arrays o entre arrays

In [54]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)

lista += [1]
print(lista)


[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [55]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8)
print(array)
array *= 2
print(array)
array += 10
print(array)
print(array.dtype) # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [56]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_2 / array_1)


[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


**3.1 Broadcasting**

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande ->[Documentación de NumPy: Broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

**3..2 Operadores unarios y binarios**

| Tipo de operación | Función | Descripción |
|-------------------|---------|-------------|
| Unario | `abs` | Valor absoluto de cada elemento. |
| Unario | `sqrt` | Raíz cuadrada de cada elemento. |
| Unario | `exp` | Calcula \(e^x\), donde *x* es cada elemento. |
| Unario | `log`, `log10`, `log2` | Calcula logaritmos en distintas bases de cada elemento. |
| Unario | `sign` | Retorna el signo de cada elemento (-1 para negativo, 0 para cero y 1 para positivo). |
| Unario | `ceil` | Redondea cada elemento hacia arriba. |
| Unario | `floor` | Redondea cada elemento hacia abajo. |
| Unario | `isnan` | Indica si cada elemento es `NaN`. |
| Unario | `cos`, `sin`, `tan` | Aplica funciones trigonométricas a cada elemento. |

| Tipo de operación | Función | Descripción |
|-------------------|---------|-------------|
| Unario | `arccos`, `arcsin`, `arctan` | Calcula las funciones trigonométricas inversas de cada elemento. |
| Binario | `add` | Suma dos arrays elemento por elemento. |
| Binario | `subtract` | Resta dos arrays elemento por elemento. |
| Binario | `multiply` | Multiplica dos arrays elemento por elemento. |
| Binario | `divide` | Divide dos arrays elemento por elemento. |
| Binario | `maximum`, `minimum` | Retorna el valor máximo o mínimo de cada pareja de elementos. |
| Binario | `equal`, `not_equal` | Compara si cada pareja de elementos es igual o diferente. |
| Binario | `greater`, `greater_equal`, `less`, `less_equal` | Compara cada pareja de elementos usando los operadores `>`, `>=`, `<` y `<=`, respectivamente. |

In [57]:
# ejemplos de operadores
array = np.arange(5)
print(array)
np.sqrt(array)


[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])
print(array1)
print(array2)
print(np.greater(array1,array2))
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


**4. Estadistica descriptiva**

• Importante saber la naturaleza de los datos

• Valores máximos, mínimos, distribución, etc.


| Función | Descripción |
|----------|-------------|
| `sum(arr)` | Suma todos los elementos del array `arr`. |
| `mean(arr)` | Calcula la media aritmética de los elementos de `arr`. |
| `std(arr)` | Calcula la desviación estándar de los elementos de `arr`. |
| `cumsum(arr)` | Devuelve un array con la suma acumulada de los elementos. |
| `cumprod(arr)` | Devuelve un array con el producto acumulado de los elementos. |
| `min(arr)`, `max(arr)` | Devuelve el valor mínimo y máximo del array `arr`. |
| `any(arr)` | En un array booleano, devuelve `True` si al menos un elemento es `True`. |
| `all(arr)` | En un array booleano, devuelve `True` si todos los elementos son `True` (o distintos de cero en arrays numéricos). |
| `unique(arr)` | Devuelve un array con los valores únicos de `arr`. |
| `in1d(arr1, arr2)` | Devuelve un array booleano indicando si cada elemento de `arr1` está presente en `arr2`. |
| `union1d(arr1, arr2)` | Devuelve la unión de los elementos de ambos arrays. |
| `intersect1d(arr1, arr2)` | Devuelve la intersección de los elementos de ambos arrays. |

In [59]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())


[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [60]:
# any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores␣<> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [61]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())


[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


**5 Algebra Lineal**

• numpy.linalg contiene funciones para álgebra lineal

• dot product, multiplicación de matrices, cálculo del determinante, factorizaciones…

| Función | Descripción |
|---------|-------------|
| `dot(mat1, mat2)` | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas. |
| `matmul(mat1, mat2)` | Devuelve el producto entre dos matrices. |
| `trace(mat)` | Calcula la suma de los elementos de la diagonal principal de una matriz. |
| `det(mat)` | Devuelve el determinante de una matriz. |
| `eig(mat)` | Calcula los autovalores y autovectores de una matriz cuadrada `mat`. |
| `inv(mat)` | Devuelve la matriz inversa de una matriz dada. |
| `qr(mat)` | Calcula la factorización QR de una matriz. |
| `solve(A, b)` | Resuelve el sistema de ecuaciones lineales `Ax = b` cuando `A` es una matriz cuadrada. |
| `transpose(mat)` | Devuelve la transpuesta de una matriz. |


In [62]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)
print(A)
print(B)
print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [63]:
import numpy.linalg as lg
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x
a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])
print(a)
print(b)
x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')
print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))


[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [64]:
#matriz identidad
I = np.identity(4)
print(I)
A = np.arange(16).reshape(4,4)
print(A)
print(np.matmul(A,I))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


**6 Filtrado de datos**

• Filtrar y modificar datos numéricos con np.where

• Retorna A o B en función de una condición en una array

In [66]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
mask = prices < 1
print(prices[prices < 1]) #slicing condicional

# mask con los elementos menores de 1
# mask = np.where(prices < 1, True, False)
# print(mask)
# print(prices[mask])

# prices[mask] = 1.0
# print(prices)

print(np.where(prices < 1, 1.0, prices))


[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]


In [69]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

print(id(data))
print(id(data_clean))


[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]
[  10.   12. -143.    0.    1.   -3.]
2036846266432
2036846419696


In [71]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
credits = np.where(bank_transfers_values > 0) # array de índices para los que␣la condición es True
print(credits)
print(bank_transfers_values[credits]) # es igual que␣bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [72]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)
rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)
daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)
final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)


[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


**7 Números aleatorios**

• Python módulo random

In [74]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores


0.08285379423582384
4
2.198795832019984


In [75]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)


'Eevee'

**7.1 NumPy.random**

• Generar fácilmente listas con valores aleatorios

In [76]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las␣dimensiones)

0.8470295955214044
1
[[3 1 0 3]
 [0 0 0 2]]


In [77]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0,␣desviación 1)
print(np.random.randn(4,2))


[[ 0.90316853  2.0423381 ]
 [-0.05867682  0.10059512]
 [ 1.41458327 -0.26596381]
 [-0.37229041  0.62565962]]


In [78]:
 # otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias␣esperadas, retornar 'size' valores


1
1.9664506959829875
[[1 3]
 [2 3]]


**7.2 Random seed**
• Números pseudo-aleatorios

• Ordenadores generan números a partir de ecuaciones

• Basadas en un número inicial (seed)

• Bueno para reproducibilidad de experimentos

In [79]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())

print()

for i in range(6):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())


0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


**8 Escritura y lectura de ndarrays a archivos**

• Para futuro acceso

• Compartir datos con otros

• Formato *.npy

In [80]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")
values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)


[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [81]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [85]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")

values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz

In [86]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))
print(npzfile.files)

for key in npzfile.files: # array.files contiene el nombre de las arrays␣(arr_0, arr_1...)
     print(npzfile[key])


<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[8 8 1]
 [6 3 4]
 [1 8 0]]
[[2 1]
 [0 3]]
[[15  2  4  1]
 [ 6 10  3  4]
 [11 12  3  1]
 [ 4  2  3  4]]


**8.0.1 ¿Por qué molestarse con .npy?**

• Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)

• ¿Para qué escribir los datos de nuevo?


In [90]:
import os
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)


In [92]:
%%timeit  # magic function jupyter

with open(ruta_csv, 'r') as f:
    data_str = f.read()

data = data_str.split(',')
data_array = np.array(data, dtype=np.int8).reshape(1000, 1000)


255 ms ± 8.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [93]:
%%timeit
data = np.load(ruta_npy)


566 μs ± 20.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [95]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")


732 ms ± 29.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**8.0.2 velocidad + simplicidad vs memoria**

**8.1 Ejercicios**

• Ejercicios para practicar NumPy: https://github.com/rougier/numpy100/blob/master/100_Numpy_exercises.ipynb

**1. IMPORTAR NumPy**


In [97]:
import numpy as np

**2. Ejecutar el archivo inicial**

In [98]:
%run initialise.py

Exception: File `'initialise.py'` not found.

In [99]:
#ejercicio 3
# crear un vector de ceros de tamaño 10.
vector = np.zeros(10)

print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [100]:
#Ejercicio 4 
#Encontrar el tamaño dde memoria que ocupa un array
array = np.zeros((10,10))

print(array.nbytes)

800


In [101]:
#Ejercicio 5 
#Obtener la documentacion de la funcion de numpy
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

In [102]:
#ejercicio 6 
# Crear un vector de cerod e tamaño 10 pero el quinto debe ser 1 
vector = np.zeros(10)

vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [104]:
#ejercicio 7
#crear un vector con valores de 10 al 49ç
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [105]:
#ejercicio 8
#invertir un vector
Z = np.arange(10)

Z = Z[::-1]

print(Z)

[9 8 7 6 5 4 3 2 1 0]


In [106]:
#ejercicio 9
#crear una matriz 3*3 con valores 0 al 8
Z = np.arange(9).reshape(3,3)

print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [107]:
#ejercicio 10
#encontrar indice de elementos diferentes de cero
Z = np.array([1,2,0,0,4,0])

indices = np.nonzero(Z)

print(indices)

(array([0, 1, 4]),)


In [108]:
#ejercicio 11
#crear una matriz identica a 3*3
Z = np.eye(3)

print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
#ejercicio 12
#crear array 3*3*3 con valores aletorios
Z = np.random.random((3,3,3))

print(Z)

[[[0.38340907 0.5103548  0.96110308]
  [0.37151262 0.01236941 0.85970689]
  [0.11111075 0.47833904 0.84998003]]

 [[0.51473797 0.44660783 0.80047642]
  [0.02039138 0.57261865 0.41138362]
  [0.9851368  0.80140153 0.0539621 ]]

 [[0.19047777 0.45241885 0.70294208]
  [0.33204815 0.3599832  0.92147057]
  [0.95363051 0.40768573 0.89857115]]]


In [110]:
#ejercicio 13
#Crear un array 10x10 aleatorio y encontrar mínimo y máximo
Z = np.random.random((10,10))

print("Valor mínimo:", Z.min())
print("Valor máximo:", Z.max())

Valor mínimo: 0.012848073980403552
Valor máximo: 0.997225466562922


In [111]:
#ejercicio 14
#Crear un array 2D con 1 en los bordes y 0 en el interior
Z = np.ones((5,5))

Z[1:-1,1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
#ejercicio 15
#Crear un vector aleatorio de tamaño 30 y encontrar la media
Z = np.random.random(30)

print("Media:", Z.mean())

Media: 0.5399391982319982


In [113]:
#ejercicio 16
#Agregar un borde de ceros alrededor de un array existente
Z = np.ones((3,3))

print(Z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [114]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [115]:
#ejercicio 17
#¿Cuál es el resultado de estas expresiones?
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [116]:
#ejercicio 18
#Crear una matriz 5x5 con valores 1,2,3,4 debajo de la diagonal
Z = np.diag(1+np.arange(4), k=-1)

print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [117]:
#ejercicio 19
#Crearuna matriz 8x8 tipo tablero de ajedrez
Z = np.zeros((8,8), dtype=int)

Z[1::2,::2] = 1
Z[::2,1::2] = 1

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [118]:
#ejercicio 20
#Array de forma (6,7,8), encontrar la posición del elemento 100
Z = np.arange(6*7*8).reshape(6,7,8)

print(Z.shape)

(6, 7, 8)


In [119]:
#ejercicio 21
#Crear una matriz tablero de ajedrez 8x8 usando tile
import numpy as np

Z = np.tile(np.array([[0,1],[1,0]]), (4,4))

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [120]:
#ejercicio 22
#Normalizar una matriz aleatoria 5x5
Z = np.random.random((5,5))

Z = (Z - Z.mean()) / Z.std()

print(Z)

[[-0.62735452  1.14152832 -1.38897243 -0.85750269 -0.13862858]
 [-1.24663524 -0.97334192  1.29330965 -0.37198659 -0.91778682]
 [ 1.309604    0.34843867  0.55554647  1.46152468  0.84039989]
 [-0.75296147 -1.6596223   0.25645639  0.81756396  1.16605225]
 [-1.01727427  0.55731361  1.63768647 -0.77754911 -0.65580845]]


In [121]:
#ejercicio 23
#Crear un tipo de dato personalizado para color RGBA
color = np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)
])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [122]:
#ejercicio 24
#multiplicar una matriz 5*3 por matriz 3*2
A = np.random.random((5,3))

B = np.random.random((3,2))

C = np.dot(A,B)

print(C)

[[0.93767058 0.83146142]
 [0.72627271 0.8746539 ]
 [0.40664317 0.44584027]
 [0.28686567 0.39598129]
 [0.3998871  0.52802893]]


In [123]:
#ejercicio 25
#cambiar a negativo los valoress entre 3 y 8 
Z = np.arange(11)

print("Original:", Z)

Z[(Z >= 3) & (Z <= 8)] *= -1

print("Modificado:", Z)

Original: [ 0  1  2  3  4  5  6  7  8  9 10]
Modificado: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [124]:
#ejercicio 26
#resultado de siguente codigo 
print (sum(range(5), -1))

from numpy import * 

print(sum(range(5),-1))

9
10


In [126]:
#ejercicio 27
#que expreciones son validad para un vector entero
Z = np.arange(5)

In [127]:
Z**Z       # válido
2 << Z >> 2 # válido
Z <- Z     # válido (comparación)
1j*Z       # válido
Z/1/1      # válido
Z<Z>Z      # inválido

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [129]:
#ejercico 28 
#resultado de expresiones con NaN
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8728\3335914039.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8728\3335914039.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8728\3335914039.py:7: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [130]:
#ejercico 29
#redondear alejandose de cero un array de flotantes 

Z = np.array([1.2, -1.7, 3.5, -4.3])

Z = np.copysign(np.ceil(np.abs(Z)), Z)

print(Z)

[ 2. -2.  4. -5.]


In [131]:
#ejercico 30
#Encontrar valores comunes entre dos arrays
A = np.array([1,2,3,4,5])

B = np.array([3,4,5,6,7])

resultado = np.intersect1d(A,B)

print(resultado)

[3 4 5]


In [132]:
#31. Ignorar todas las advertencias de NumPy
import numpy as np

np.seterr(all="ignore")

Z = np.array([1,0])

print(Z/0)

[inf nan]


In [133]:
#32. Comparar sqrt(-1) con emath.sqrt(-1)
import numpy as np

print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [134]:
#33. Obtener las fechas de ayer, hoy y mañana
import numpy as np

hoy = np.datetime64('today')

ayer = hoy - np.timedelta64(1,'D')

manana = hoy + np.timedelta64(1,'D')

print("Ayer:", ayer)
print("Hoy:", hoy)
print("Mañana:", manana)

Ayer: 2026-07-05
Hoy: 2026-07-06
Mañana: 2026-07-07


In [135]:
#34. Obtener todas las fechas del mes de julio de 2016
julio = np.arange(
    np.datetime64('2016-07-01'),
    np.datetime64('2016-08-01')
)

print(julio)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [136]:
#35. Calcular (A+B)*(-A/2) sin crear copias
A = np.ones(3)
B = np.ones(3)

np.add(A,B,out=A)

np.divide(A,-2,out=A)

print(A)

[-1. -1. -1.]


In [137]:
#36. Extraer la parte entera de números positivos usando 4 métodos
Z = np.random.uniform(0,10,10)

print(Z)

[4.47310154 0.27528463 2.78977672 0.751705   0.47738377 8.6358558
 7.1431759  8.304377   1.32905796 3.6528646 ]


In [138]:
print(Z.astype(int))

[4 0 2 0 0 8 7 8 1 3]


In [139]:
print(np.floor(Z))

[4. 0. 2. 0. 0. 8. 7. 8. 1. 3.]


In [140]:
print(np.trunc(Z))

[4. 0. 2. 0. 0. 8. 7. 8. 1. 3.]


In [141]:
print(Z - Z % 1)

[4. 0. 2. 0. 0. 8. 7. 8. 1. 3.]


In [142]:
#37. Crear matriz 5x5 con valores de fila de 0 a 4
Z = np.zeros((5,5), dtype=int)

Z += np.arange(5)

print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [143]:
#38. Crear un array usando una función generadora
def generador():
    for i in range(10):
        yield i

Z = np.fromiter(generador(), dtype=float)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [144]:
#39. Crear un vector de tamaño 10 con valores entre 0 y 1 sin incluir extremos
Z = np.linspace(0,1,12)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [145]:
#40. Crear un vector aleatorio de tamaño 10 y ordenarlo
Z = np.random.random(10)

print("Antes:")
print(Z)

Z.sort()

print("Después:")
print(Z)

Antes:
[0.91321754 0.43338789 0.92565181 0.96136808 0.00660811 0.43293059
 0.58311263 0.34882757 0.37603202 0.35582158]
Después:
[0.00660811 0.34882757 0.35582158 0.37603202 0.43293059 0.43338789
 0.58311263 0.91321754 0.92565181 0.96136808]


In [146]:
#41. ¿Cómo sumar un array pequeño más rápido que np.sum?
import numpy as np

Z = np.arange(10)

resultado = sum(Z)

print(resultado)

45


In [147]:
#42. Comparar si dos arrays aleatorios son iguales
A = np.random.randint(0,10,10)

B = np.random.randint(0,10,10)

print(np.array_equal(A,B))

False


In [148]:
#43. Hacer un array inmutable (solo lectura)
Z = np.zeros(10)

Z.flags.writeable = False

Z[0] = 1

ValueError: assignment destination is read-only

In [149]:
#44. Convertir coordenadas cartesianas a polaresç
Z = np.random.random((10,2))

x = Z[:,0]
y = Z[:,1]

radio = np.sqrt(x**2 + y**2)

angulo = np.arctan2(y,x)

print("Radio:")
print(radio)

print("Ángulo:")
print(angulo)

Radio:
[0.8025627  1.21789625 0.62286834 1.04030952 0.50467478 0.95071785
 1.04419275 1.01216907 1.25219053 0.73884626]
Ángulo:
[1.4606249  0.92913149 1.47831001 0.53109403 0.93724618 1.47007199
 1.0641634  1.0696761  0.91747467 0.80352067]


In [150]:
#45. Crear vector aleatorio y cambiar el máximo por 0
Z = np.random.random(10)

print("Original:")
print(Z)

Z[Z.argmax()] = 0

print("Modificado:")
print(Z)

Original:
[0.89533366 0.07107016 0.34445056 0.15688357 0.70314955 0.86458372
 0.52913005 0.52633773 0.3215009  0.48665962]
Modificado:
[0.         0.07107016 0.34445056 0.15688357 0.70314955 0.86458372
 0.52913005 0.52633773 0.3215009  0.48665962]


In [151]:
#46. Crear un array estructurado con coordenadas x,y
Z = np.zeros(10, [
    ('x', float),
    ('y', float)
])

print(Z)

[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
 (0., 0.) (0., 0.)]


In [152]:
#47. Construir matriz de Cauchy
X = np.arange(5)

Y = X + 0.5

C = 1 / np.subtract.outer(X,Y)

print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


In [153]:
#48. Mostrar valores mínimos y máximos de tipos NumPy
for dtype in [np.int8, np.int32, np.float32, np.float64]:

    print(dtype)

    print(np.iinfo(dtype) if np.issubdtype(dtype,np.integer)
          else np.finfo(dtype))

<class 'numpy.int8'>
Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

<class 'numpy.int32'>
Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

<class 'numpy.float32'>
Machine parameters for float32
---------------------------------------------------------------
precision = 6   resolution = 1e-06
machep = -23   eps =        1.1920929e-07
negep =  -24   epsneg =     5.9604645e-08
minexp = -126   tiny =       1.1754944e-38
maxexp = 128   max =        3.4028235e+38
nexp =   8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1e-45
---------------------------------------------------------------

<class 'numpy.float64'>
Machine parameters for float64
---------------------------------------------------

In [154]:
#49. Imprimir todos los valores de un array
np.set_printoptions(threshold=np.inf)

Z = np.arange(100)

print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [155]:
#50. Encontrar el valor más cercano a un número dado
Z = np.array([1,3,5,7,9])

valor = 5.2

indice = np.abs(Z - valor).argmin()

print(Z[indice])

5


In [156]:
#51. Crear un array estructurado con posición (x,y) y color (r,g,b)
import numpy as np

Z = np.zeros(10, [
    ('x', float),
    ('y', float),
    ('r', float),
    ('g', float),
    ('b', float)
])

print(Z)

[(0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)
 (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)
 (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)
 (0., 0., 0., 0., 0.)]


In [157]:
#52. Calcular distancias punto a punto de una matriz (100,2)
Z = np.random.random((100,2))

distancias = np.sqrt(
    np.sum((Z[:,np.newaxis] - Z)**2, axis=-1)
)

print(distancias)

[[0.         0.70214231 0.36838333 0.42991358 0.52354517 0.68992733
  0.73619204 0.3430457  0.03568265 0.7517575  0.37794169 0.57720959
  0.8746544  0.09642404 0.39972478 1.00364775 0.10603719 0.76299587
  0.63518109 0.8193734  0.43667449 0.70433127 0.42119859 0.7481616
  0.72818254 0.81998363 0.69450663 0.62053548 0.83113785 0.57586705
  0.69822936 0.59751695 0.15297408 0.78029491 0.87565778 0.15494978
  0.23577267 0.38556239 0.30518973 0.25533327 0.28613241 1.05810679
  0.43404538 0.76964981 0.75217996 0.70962811 0.7796256  1.08107418
  0.53619604 0.23332645 0.70205499 0.2144142  0.45350161 0.97019765
  0.72442122 0.21198964 1.02615957 0.51625969 0.614734   0.63977555
  0.66541251 0.44917038 0.3836716  0.82577864 0.46572167 0.51952168
  0.42552346 0.34255381 0.17717422 0.13025628 0.28104353 0.78643557
  0.5528474  0.7769502  0.8297945  0.32890267 0.5954088  1.09245145
  0.52297779 0.16416081 0.16200856 0.33984639 1.05719963 0.6453552
  0.84137786 0.28908335 0.58884794 0.17635856 0.46

In [158]:
#53. Convertir un array float32 a int32 en el mismo lugar
Z = np.arange(10, dtype=np.float32)

print(Z)

Z = Z.astype(np.int32)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [159]:
#54. Leer un archivo con valores faltantes
from io import StringIO

texto = StringIO("""
1,2,3,4,5
6,,,7,8
,,9,10,11
""")

Z = np.genfromtxt(texto, delimiter=",", filling_values=0)

print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


In [160]:
#55. Equivalente de enumerate para arrays NumPy
Z = np.array([10,20,30,40])

for indice, valor in np.ndenumerate(Z):
    print(indice, valor)

(0,) 10
(1,) 20
(2,) 30
(3,) 40


In [161]:
#56. Crear una matriz 2D tipo distribución Gaussiana
x, y = np.meshgrid(
    np.linspace(-1,1,10),
    np.linspace(-1,1,10)
)

D = np.sqrt(x*x + y*y)

sigma = 0.5

G = np.exp(-(D**2)/(2*sigma**2))

print(G)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

In [162]:
#57. Colocar aleatoriamente p elementos en un array 2D
Z = np.zeros((10,10))

p = 10

indices = np.random.choice(
    100,
    p,
    replace=False
)

Z.flat[indices] = 1

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


In [163]:
#58. Restar la media de cada fila de una matriz
Z = np.random.random((5,5))

Z = Z - Z.mean(axis=1, keepdims=True)

print(Z)

[[-3.72978942e-02  2.97657772e-01 -1.10767039e-01  1.09019011e-01
  -2.58611849e-01]
 [ 2.98497593e-01  2.40006029e-01  5.91578292e-04 -2.64207967e-01
  -2.74887233e-01]
 [-2.33860821e-01 -2.09139786e-01  3.96367239e-02 -3.49556190e-02
   4.38319502e-01]
 [ 1.16670001e-01 -6.04348209e-02 -2.41747785e-01 -3.22805910e-02
   2.17793195e-01]
 [-2.81744530e-01 -3.37915550e-01  2.68642002e-01  5.98035045e-01
  -2.47016967e-01]]


In [164]:
#59. Ordenar un array por la columna n
Z = np.random.randint(0,10,(5,3))

print("Original:")
print(Z)

Z = Z[Z[:,1].argsort()]

print("Ordenado:")
print(Z)

Original:
[[2 8 0]
 [8 7 3]
 [4 2 8]
 [5 6 0]
 [8 8 1]]
Ordenado:
[[4 2 8]
 [5 6 0]
 [8 7 3]
 [2 8 0]
 [8 8 1]]


In [165]:
#60. Saber si una matriz tiene columnas vacías (ceros)
Z = np.array([
    [1,0,3],
    [4,0,6],
    [7,0,9]
])

resultado = np.any(Z, axis=0)

print(resultado)

[ True False  True]


In [166]:
#61. Encontrar el valor más cercano a un valor dado en un array
import numpy as np

Z = np.array([0.1, 0.3, 0.7, 1.2])

valor = 0.5

indice = np.abs(Z - valor).argmin()

print("Valor más cercano:", Z[indice])

Valor más cercano: 0.7


In [167]:
#62. Sumar dos arrays con formas (1,3) y (3,1) usando un iterador
A = np.arange(3).reshape(1,3)

B = np.arange(3).reshape(3,1)

resultado = np.nditer([A,B,None])

for x,y,z in resultado:
    z[...] = x+y

print(resultado.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [168]:
#63. Crear una clase de array que tenga atributo name
class ArrayNumpy(np.ndarray):

    def __new__(cls, array, name=""):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj


Z = ArrayNumpy([1,2,3], name="Mi array")

print(Z)
print(Z.name)

[1 2 3]
Mi array


In [169]:
#64. Sumar 1 a elementos indicados por otro vector
Z = np.zeros(10)

indices = [1,3,5,3]

np.add.at(Z, indices, 1)

print(Z)

[0. 1. 0. 2. 0. 1. 0. 0. 0. 0.]


In [170]:
#65. Acumular valores según una lista de índices
Z = np.array([1,2,3,4])

indices = [0,1,0,1]

resultado = np.zeros(2)

np.add.at(resultado, indices, Z)

print(resultado)

[4. 6.]


In [171]:
#66. Encontrar cantidad de colores únicos en una imagen
imagen = np.random.randint(
    0,256,(10,10,3)
)

colores = imagen.reshape(-1,3)

cantidad = len(np.unique(colores, axis=0))

print("Colores únicos:", cantidad)

Colores únicos: 100


In [172]:
#67. Sumar los últimos dos ejes de un array de 4 dimensiones
Z = np.random.randint(
    0,10,(2,3,4,5)
)

resultado = Z.sum(axis=(-2,-1))

print(resultado)

[[ 93  41  69]
 [100  75  93]]


In [173]:
#68. Calcular medias de grupos usando índices
D = np.array([1,2,3,4,5,6])

S = np.array([0,0,1,1,2,2])

resultado = np.bincount(S, weights=D) / np.bincount(S)

print(resultado)

[1.5 3.5 5.5]


In [174]:
#69. Obtener la diagonal de un producto punto
A = np.random.random((3,3))

B = np.random.random((3,3))

resultado = np.diag(np.dot(A,B))

print(resultado)

[0.77282035 0.55007586 1.49046116]


In [175]:
#resultado forma mas rapida
resultado = np.einsum('ij,ji->i',A,B)

print(resultado)

[0.77282035 0.55007586 1.49046116]


In [177]:
#70. Insertar tres ceros entre cada valor de un vector
Z = np.array([1,2,3,4,5])

In [178]:
R = np.zeros(len(Z)*4-3)

R[::4] = Z

print(R)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [179]:
#71. Multiplicar un array (5,5,3) por otro (5,5)
import numpy as np

A = np.ones((5,5,3))

B = 2*np.ones((5,5))

resultado = A * B[:,:,np.newaxis]

print(resultado.shape)

(5, 5, 3)


In [180]:
#72. Intercambiar dos filas de un array
Z = np.arange(25).reshape(5,5)

print("Original:")
print(Z)

Original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [182]:
#73. Encontrar segmentos únicos de triángulos
triangulos = np.array([
    [0,1,2],
    [0,2,3],
    [0,3,1]
])

In [183]:
segmentos = np.vstack([
    triangulos[:,[0,1]],
    triangulos[:,[1,2]],
    triangulos[:,[2,0]]
])

segmentos = np.sort(segmentos, axis=1)

segmentos = np.unique(segmentos, axis=0)

print(segmentos)

[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]]


In [184]:
#74. Crear un array desde un bincount
C = np.bincount([1,1,2,3,3,3])

print(C)

A = np.repeat(
    np.arange(len(C)),
    C
)

print(A)

[0 2 1 3]
[1 1 2 3 3 3]


In [185]:
#75. Calcular promedio usando una ventana deslizante
Z = np.arange(10)

ventana = 3

promedio = np.convolve(
    Z,
    np.ones(ventana)/ventana,
    mode='valid'
)

print(promedio)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [186]:
#76. Crear matriz desplazada usando un vector
Z = np.arange(10)
R = np.lib.stride_tricks.sliding_window_view(Z,3)

print(R)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [187]:
#77. Negar booleanos o cambiar signo de flotantes en el mismo array
Z = np.array([True, False, True])

np.logical_not(Z, out=Z)

print(Z)

[False  True False]


In [188]:
#para numeros 
Z = np.array([1,-2,3])

np.negative(Z, out=Z)

print(Z)

[-1  2 -3]


In [190]:
#78. Distancia de un punto a varias líneas
P0 = np.array([[0,0],[1,1]])

P1 = np.array([[1,0],[2,1]])

p = np.array([0.5,0.5])

In [191]:
v = P1-P0

w = p-P0

distancia = np.abs(
    v[:,0]*w[:,1] - v[:,1]*w[:,0]
) / np.sqrt(
    v[:,0]**2 + v[:,1]**2
)

print(distancia)

[0.5 0.5]


In [192]:
#79. Distancia de varios puntos a varias líneas
P = np.random.random((5,2))

P0 = np.random.random((3,2))

P1 = np.random.random((3,2))


v = P1-P0

distancia = np.abs(
    v[:,None,0]*(P[None,:,1]-P0[:,None,1]) -
    v[:,None,1]*(P[None,:,0]-P0[:,None,0])
) / np.sqrt(
    v[:,0]**2 + v[:,1]**2
)[:,None]

print(distancia)

[[0.29841436 0.09829832 0.0222083  0.23816804 0.10044031]
 [0.58238968 0.1895245  0.44968487 0.07424838 0.25080692]
 [0.32779341 0.04230315 0.21465806 0.3411445  0.49407849]]


In [193]:
#79. Distancia de varios puntos a varias líneas
P = np.random.random((5,2))

P0 = np.random.random((3,2))

P1 = np.random.random((3,2))


v = P1-P0

distancia = np.abs(
    v[:,None,0]*(P[None,:,1]-P0[:,None,1]) -
    v[:,None,1]*(P[None,:,0]-P0[:,None,0])
) / np.sqrt(
    v[:,0]**2 + v[:,1]**2
)[:,None]

print(distancia)


[[0.25640366 0.27804645 0.0164333  0.44806865 0.39035415]
 [0.36419887 0.16954367 0.22301362 0.78428681 0.48256716]
 [0.05348143 0.56100322 0.28684971 0.32542983 0.46466716]]


In [194]:
#80. Extraer una parte de un array centrada en un elemento
def extraer(Z, centro, tamaño, relleno=0):

    resultado = np.full(
        (tamaño,tamaño),
        relleno
    )

    x,y = centro

    inicio_x = max(x-tamaño//2,0)
    inicio_y = max(y-tamaño//2,0)

    fin_x = inicio_x+tamaño
    fin_y = inicio_y+tamaño

    resultado[:fin_x-inicio_x,:fin_y-inicio_y] = \
        Z[inicio_x:fin_x,inicio_y:fin_y]

    return resultado


Z = np.arange(25).reshape(5,5)

print(extraer(Z,(2,2),3))

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [196]:
#81. Generar una matriz con ventanas consecutivas
Z = np.arange(1,15)

In [197]:
R = np.lib.stride_tricks.sliding_window_view(Z,4)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [198]:
#82. Calcular el rango de una matriz
Z = np.random.random((5,5))

rango = np.linalg.matrix_rank(Z)

print("Rango:", rango)

Rango: 5


In [199]:
#83. Encontrar el valor más frecuente de un array
Z = np.array([1,2,3,2,4,2,5,3])

valores, cantidades = np.unique(
    Z,
    return_counts=True
)

resultado = valores[np.argmax(cantidades)]

print("Valor más frecuente:", resultado)

Valor más frecuente: 2


In [200]:
#84. Extraer bloques 3x3 de una matriz 10x10
Z = np.random.random((10,10))
bloques = np.lib.stride_tricks.sliding_window_view(
    Z,
    (3,3)
)

print(bloques.shape)

(8, 8, 3, 3)


In [201]:
#85. Crear una subclase donde Z[i,j] = Z[j,i]
class MatrizSimetrica(np.ndarray):

    def __setitem__(self, key, value):

        i,j = key

        super().__setitem__((i,j),value)

        super().__setitem__((j,i),value)


Z = np.zeros((3,3)).view(MatrizSimetrica)

Z[0,1] = 5

print(Z)

[[0. 5. 0.]
 [5. 0. 0.]
 [0. 0. 0.]]


In [202]:
#86. Sumar productos de varias matrices al mismo tiempo
p = 10
n = 3

A = np.random.random((p,n,n))

B = np.random.random((p,n,1))

resultado = np.einsum(
    'ijk,ikl->jl',
    A,
    B
)

print(resultado)

[[ 9.35527162]
 [ 9.40997901]
 [10.34000345]]


In [203]:
#87. Obtener suma de bloques 4x4 de una matriz 16x16
Z = np.arange(16*16).reshape(16,16)

resultado = Z.reshape(
    4,4,4,4
).sum(
    axis=(1,3)
)

print(resultado)

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [204]:
#88. Implementar el juego de la vida (Game of Life)
Z = np.random.randint(0,2,(10,10))

print(Z)

[[0 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 0 1 1 0 0]
 [0 1 0 1 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 1 0 1 1 0 0 0 0]
 [1 1 1 0 1 0 1 0 0 0]
 [1 1 0 1 0 0 1 1 0 1]
 [0 1 1 1 1 0 0 0 1 1]]


In [205]:
#contra vecinos 
vecinos = (
    np.roll(Z,1,0)+
    np.roll(Z,-1,0)+
    np.roll(Z,1,1)+
    np.roll(Z,-1,1)+
    np.roll(np.roll(Z,1,0),1,1)+
    np.roll(np.roll(Z,1,0),-1,1)+
    np.roll(np.roll(Z,-1,0),1,1)+
    np.roll(np.roll(Z,-1,0),-1,1)
)

Z = (vecinos==3) | ((Z==1)&(vecinos==2))

print(Z)

[[False False False False False  True  True False  True False]
 [ True False False  True False False False  True  True  True]
 [False False False  True  True  True  True False  True  True]
 [False  True False False False  True  True  True False False]
 [False False False False False False False  True False False]
 [False  True  True False False  True  True False False False]
 [ True False  True False  True  True  True False False False]
 [False False False False  True False  True  True False  True]
 [False False False False False False  True  True False False]
 [False False False False  True  True  True False False False]]


In [206]:
#89. Obtener los n valores más grandes de un array
Z = np.array([5,2,8,1,9,3])

n = 3

resultado = np.sort(Z)[-n:]

print(resultado)

[5 8 9]


In [207]:
np.partition(Z,-n)[-n:]

array([5, 8, 9])

In [208]:
#90. Construir el producto cartesiano de varios vectores
A = np.array([1,2])

B = np.array([3,4])

C = np.array([5,6])
resultado = np.array(
    np.meshgrid(A,B,C)
).T.reshape(-1,3)

print(resultado)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [209]:
#91. Crear un record array desde un array normal
import numpy as np

Z = np.array([
    [1,2],
    [3,4],
    [5,6]
])

R = np.core.records.fromarrays(
    Z.T,
    names="x,y"
)

print(R)
print(R.x)
print(R.y)

[(1, 2) (3, 4) (5, 6)]
[1 3 5]
[2 4 6]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8728\663158936.py:10: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(


In [210]:
#92. Calcular la potencia de un vector al cubo usando 3 métodos
Z = np.arange(10)

In [211]:
resultado = Z**3

print(resultado)

[  0   1   8  27  64 125 216 343 512 729]


In [212]:
#funcion power 
reesultado = np.power(z,3)

print(resultado)

[  0   1   8  27  64 125 216 343 512 729]


In [213]:
#multiplicacion
resultado = z*z*z

print(resultado)

64


In [216]:
#93. Encontrar filas de A que contienen elementos de B
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [1,3,5]
])

B = np.array([
    [3,1],
    [8,7]
])

In [217]:
resultado = []

for fila in B:
    resultado.append(
        np.where(
            np.all(np.isin(A,fila),axis=1)
        )[0]
    )

print(resultado)

[array([], dtype=int64), array([], dtype=int64)]


In [218]:
#94. Extraer filas con valores diferentes
Z = np.array([
    [2,2,3],
    [1,1,1],
    [4,5,6],
    [7,7,7]
])
resultado = Z[np.any(Z[:,1:] != Z[:,:-1],axis=1)]

print(resultado)

[[2 2 3]
 [4 5 6]]


In [219]:
#95. Convertir un vector de enteros a representación binaria
Z = np.array([1,2,3,4,5])
binario = (
    (Z[:,None] & (1 << np.arange(8))) > 0
)

print(binario)

[[ True False False False False False False False]
 [False  True False False False False False False]
 [ True  True False False False False False False]
 [False False  True False False False False False]
 [ True False  True False False False False False]]


In [220]:
#96. Extraer filas únicas de una matriz
Z = np.array([
    [1,2],
    [3,4],
    [1,2],
    [5,6]
])

resultado = np.unique(
    Z,
    axis=0
)

print(resultado)

[[1 2]
 [3 4]
 [5 6]]


In [221]:
#97. Usar einsum equivalente a operaciones comunes
A = np.array([1,2,3])

B = np.array([4,5,6])

np.einsum('i,i',A,B)

np.int64(32)

In [223]:
#98. Muestrear una ruta con puntos equidistantes
X = np.array([0,1,2,3,4])

Y = np.array([0,2,4,6,8])

distancia = np.sqrt(
    np.diff(X)**2 +
    np.diff(Y)**2
)

acumulada = np.insert(
    np.cumsum(distancia),
    0,
    0
)

print(acumulada)

[0.         2.23606798 4.47213595 6.70820393 8.94427191]


In [224]:
#99. Seleccionar filas que representan una distribución multinomial
n = 5

X = np.array([
    [2,1,2],
    [3,3,1],
    [1,2,2],
    [5,1,1]
])
resultado = X[
    (X.sum(axis=1)==n) &
    (X.astype(int)==X).all(axis=1)
]

print(resultado)

[[2 1 2]
 [1 2 2]]


In [226]:
#100. Intervalo de confianza Bootstrap del 95%
X = np.random.randn(100)
N = 1000
medias = []

for i in range(N):

    muestra = np.random.choice(
        X,
        size=len(X),
        replace=True
    )

    medias.append(
        muestra.mean()
    )


intervalo = np.percentile(
    medias,
    [2.5,97.5]
)

print("Intervalo de confianza 95%:")
print(intervalo)

Intervalo de confianza 95%:
[-0.11472657  0.26751635]
